---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: stretch64
    box: debian/stretch64
  - name: jessie64
    box: debian/jessie64
  - name: xenial64
    box: ubuntu/xenial64
  - name: bionic64
    box: ubuntu/bionic64
provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
