---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    force: false
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
verifier:
  name: goss
  directory: ../default/tests/
