---
name: Integration
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".*"
      - ".github/**"
      - "README.md"
  schedule:
    # * is a special character in YAML so you have to quote this string
    # first of each month
    - cron: "0 0 1 * *"

jobs:
  integration:
    name: Integration
    uses: systemli/github-ansible-workflow/.github/workflows/ansible-integration-workflow.yaml@molecule4
    with:
      distros: '[ "debian11", "debian10" ]'
      role-dependencies: |
        - src: systemli.apt_repositories
      molecule-config: |
        ---
        driver:
          name: docker
        platforms:
          - name: instance
            image: "geerlingguy/docker-\$\{MOLECULE_DISTRO:-debian11\}-ansible:latest"
            command: "\$\{MOLECULE_DOCKER_COMMAND:-'/usr/sbin/init'\}"
            volumes:
              - /sys/fs/cgroup:/sys/fs/cgroup:ro
            privileged: true
            pre_build_image: true
        provisioner:
          name: ansible
          playbooks:
            converge: ../default/converge.yml
